# On every push this script is executed
on: push
name: Build and deploy GH Pages

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      resume: ${{ steps.filter.outputs.resume }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            resume:
              - 'content/resume/*.tex'

  build-resume:
    needs: changes
    if: needs.changes.outputs.resume == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: content/resume/resume.tex
      - run: mv resume.pdf static/resume.pdf
      
      - name: Upload resume artifact
        if: needs.changes.outputs.resume == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: static/resume.pdf

  build-site:
    needs: [changes, build-resume]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download resume artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: static/
          
      - uses: actions/checkout@v4

      - name: build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
