# On every push this script is executed
on: push
name: Build and deploy GH Pages

jobs:
  build-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Compile resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: content/resume/resume.tex

      - name: Move PDF into static/
        run: |
         mkdir -p static/
         mv resume.pdf static/resume.pdf
      
      - name: Upload resume artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: static/resume.pdf

  build-site:
    needs: build-resume
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download resume artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: static/

      - name: Build and deploy site
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
