# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      resume: ${{ steps.filter.outputs.resume }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            resume:
              - 'content/resume/*.tex'
  build-site:
    needs: [build-resume, changes]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-resume:
    needs: changes
    if: needs.changes.outputs.resume == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: content/resume/resume.tex
      - name: Commit and push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv resume.pdf content/resume/
          git fetch
          git checkout gh-pages
          git add content/resume/resume.pdf
          git commit -m "GitHub Actions: Update compiled PDF" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
